### ISSUE TITLE
Добавить тестирование в проект

### ISSUE THREAD

**Issue by Spotika** [elansteam/backend#17]

**Comment by difhel** [comment]
А что сейчас не так? Вроде бы pytest прикрутили, даже в master слили

**Comment by difhel** [comment]
Починить тестирование!!!

![Image](https://github.com/elansteam/backend/assets/78644136/84c0ca50-9dfd-44b5-ac7e-6c75751989b0)

**Comment by Spotika** [comment]
> Починить тестирование!!!
> 
> ![Image](https://private-user-images.githubusercontent.com/78644136/290887975-84c0ca50-9dfd-44b5-ac7e-6c75751989b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2Njc4OTMsIm5iZiI6MTcwMjY2NzU5MywicGF0aCI6Ii83ODY0NDEzNi8yOTA4ODc5NzUtODRjMGNhNTAtOWRmZC00NGI1LWFjN2UtNmM3NTc1MTk4OWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE1VDE5MTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYmVlOGExYTQ5ZGZiZDEwYTUzM2Q1OGFjMjU0NjNiNGM5OTIwMDBkNmM2NjlkYjIzMjU2M2ExNzRkNzM4NGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vCmcyMi8UlthlxYghShm70iSNzeJr9KrAeBwP8WbzBI)

Для того, чтобы это починить следует реализовать валидацию для объекта ObjectID, так как Pydantic не может валидировать этот объект. Я вижу решение в уходе от идеи ObjectId и переходе на автоинкремент и заменить поле `id: ObjectId` на `id: int`.

**Comment by difhel** [comment]
fixed in #21
